theme: jekyll-theme-chirpy

lang: en

title: AI @ Greece

timezone: Europe/Athens

tagline: A text-focused Jekyll theme # it will display as the subtitle


description: >- # used by seo meta and the atom feed
  A minimal, responsive and feature-rich Jekyll theme for technical writing.

url: ""

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: your_full_name
  email: example@domain.com # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://github
    
theme_mode: # [light | dark].com/username 

avatar: "/commons/avatar.jpg"

include: # ['_pages', '_posts', '_layout']
exclude: # ['files'] # ['_includes']
